force-app/main/default/objects/Outbox_Message__c/Outbox_Message__c.object-meta.xml
<CustomObject>
    <description>Stores Outbox &quot;Message&quot;.  Each Message may trigger 0 or more Outbox record</description>
    <label>Outbox Message</label>
    <nameField>
        <displayFormat>OE-{0000}</displayFormat>
        <label>Outbox Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbox Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Outbox_Message__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of the message to fire.  Much match the DeveloperName of an Message Definition</description>
    <inlineHelpText>The type of the message to fire.  Much match the DeveloperName of an Message Definition</inlineHelpText>
    <label>Message Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TB_Application__mdt/TB_Application__mdt.object-meta.xml
<CustomObject>
    <description>An entity which can subscribe to messages</description>
    <label>TB Application</label>
    <pluralLabel>TB Applications</pluralLabel>
</CustomObject>

force-app/main/default/objects/TB_Message_Definition__mdt/TB_Message_Definition__mdt.object-meta.xml
<CustomObject>
    <description>Defines which messages can be fired in the org</description>
    <label>TB Message Definition</label>
    <pluralLabel>TB Message Definitions</pluralLabel>
</CustomObject>

force-app/main/default/objects/TB_Message_Subscription__mdt/TB_Message_Subscription__mdt.object-meta.xml
<CustomObject>
    <description
    >Defines Subscriptions to each message.  Any time an message is fired, an outbox record will be setup for each Active subscription</description>
    <label>Message Subscription</label>
    <pluralLabel>Message Subscriptions</pluralLabel>
</CustomObject>

force-app/main/default/objects/TB_Message_Subscription__mdt/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <description>Application this subscription is for</description>
    <inlineHelpText>Application this subscription is for</inlineHelpText>
    <label>Application</label>
    <referenceTo>TB_Application__mdt</referenceTo>
    <relationshipLabel>Message Subscriptions</relationshipLabel>
    <relationshipName>Message_Subscriptions</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/TB_Message_Subscription__mdt/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description
    >Allows Enabling/Disabling a subscription.  Determines if outbox records are created at the time the Message is inserted.  Outbox records that are already created will still attempt to send.</description>
    <inlineHelpText
    >Allows Enabling/Disabling a subscription.  Determines if outbox records are created at the time the Message is inserted.  Outbox records that are already created will still attempt to send.</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TB_Message_Subscription__mdt/fields/Mark_TTL_Event__c.field-meta.xml
<CustomField>
    <fullName>Mark_TTL_Event__c</fullName>
    <description>The outbox lifecycle event which results in "TTL Offset" being applied to the record.</description>
    <inlineHelpText>The outbox lifecycle event which results in TTL being applied to the record.</inlineHelpText>
    <label>Mark TTL Event</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>created</fullName>
                <default>true</default>
                <label>created</label>
            </value>
            <value>
                <fullName>completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TB_Message_Subscription__mdt/fields/Max_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Max_Attempts__c</fullName>
    <description>Number of times to attempt the message before it is deadlettered</description>
    <inlineHelpText>Number of times to attempt the message before it is deadlettered</inlineHelpText>
    <label>Max Attempts</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TB_Message_Subscription__mdt/fields/Message_Definition__c.field-meta.xml
<CustomField>
    <fullName>Message_Definition__c</fullName>
    <description>The Message to subscribe to</description>
    <label>Message Definition</label>
    <referenceTo>TB_Message_Definition__mdt</referenceTo>
    <relationshipLabel>Message Subscriptions</relationshipLabel>
    <relationshipName>Message_Subscriptions</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/TB_Message_Subscription__mdt/fields/TTL_Offset__c.field-meta.xml
<CustomField>
    <fullName>TTL_Offset__c</fullName>
    <description>The number of minutes this record will persist in the system after either Created or Delivered (controlled by &quot;Mark TTL Event&quot; field).

Request that scheduled record deletion is setup to automatically remove records.</description>
    <inlineHelpText>The number of minutes this record will persist in the system after either Creation or Delivery.

Request that scheduled record deletion is setup to automatically remove records.</inlineHelpText>
    <label>TTL</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TB_Outbox_Message__c/TB_Outbox_Message__c.object-meta.xml
<CustomObject>
    <description>Stores Outbox &quot;Message&quot;.  Each Message may trigger 0 or more Outbox record</description>
    <label>Outbox Message</label>
    <nameField>
        <displayFormat>OE-{0000}</displayFormat>
        <label>Outbox Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbox Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TB_Outbox_Message__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of the message to fire.  Much match the DeveloperName of an Message Definition</description>
    <inlineHelpText
    >The type of the message to fire.  Much match the DeveloperName of an Message Definition</inlineHelpText>
    <label>Message Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TB_Subscription_Outbox__c/TB_Subscription_Outbox__c.object-meta.xml
<CustomObject>
    <description>Transactional Outbox tracking for each subscriber of an message</description>
    <label>Subscription Outbox</label>
    <nameField>
        <label>Subscription Outbox Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Outboxes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TB_Subscription_Outbox__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <description>The DeveloperName of the related TB_Application__mdt</description>
    <inlineHelpText>The DeveloperName of the related TB_Application__mdt</inlineHelpText>
    <label>Application</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TB_Subscription_Outbox__c/fields/Max_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Max_Attempts__c</fullName>
    <defaultValue>3</defaultValue>
    <description>The Maximum number of times to attempt to deliver this message.</description>
    <inlineHelpText>The Maximum number of times to attempt to deliver this message.</inlineHelpText>
    <label>Max Attempts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TB_Subscription_Outbox__c/fields/Outbox_Message__c.field-meta.xml
<CustomField>
    <fullName>Outbox_Message__c</fullName>
    <description>The message this outbox item corresponds to</description>
    <inlineHelpText>The message this outbox item corresponds to</inlineHelpText>
    <label>Outbox Message</label>
    <referenceTo>TB_Outbox_Message__c</referenceTo>
    <relationshipLabel>Subscription Outboxes</relationshipLabel>
    <relationshipName>Subscription_Outboxes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TB_Subscription_Outbox__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <description
    >The subscription that this outbox message is firing for.  Should match based on name in Message Subscription Definitions</description>
    <externalId>true</externalId>
    <inlineHelpText
    >The subscription that this outbox message is firing for.  Should match based on name in Message Subscription Definitions</inlineHelpText>
    <label>Subscription</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TB_Subscription_Outbox__c/fields/TTL__c.field-meta.xml
<CustomField>
    <fullName>TTL__c</fullName>
    <description>This record will be removed once the TTL is passed.  Automatic TTL can be set via Subscription Metadata.

Requires automatic record deletion schedule job is setup.</description>
    <inlineHelpText>This record will be removed once the TTL is passed.  Automatic TTL can be set via Subscription Metadata.

Requires automatic record deletion schedule job is setup.</inlineHelpText>
    <label>Time To Live</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/TB_OutboxMessageTriggerHandler.cls
public with sharing class TB_OutboxMessageTriggerHandler {
    public void handle() {
        if (Trigger.isBefore && Trigger.isInsert) {
            beforeInsert();
        } else if (Trigger.isAfter && Trigger.isInsert) {
            afterInsert();
        }
    }

    private static void beforeInsert() {
        Map<String, TB_Message_Definition__mdt> messageDefinitions = TB_OutboxMetadataProvider.getMessageDefintionMap();
        for (TB_Outbox_Message__c outboxMessage : (List<TB_Outbox_Message__c>) Trigger.new) {
            if (!messageDefinitions.containsKey(outboxMessage.Type__c)) {
                outboxMessage.addError('The outbox message Type ' + outboxMessage.Type__c + ' does not match any message definition.  You must provide the DeveloperName of the Message Definition.');
            }
        }
    }

    private static void afterInsert() {
        Map<String, List<TB_Outbox_Message__c>> recordsByMessageType = new Map<String, List<TB_Outbox_Message__c>>();
        for (TB_Outbox_Message__c evt : (List<TB_Outbox_Message__c>) Trigger.new) {
            // group evts by type
            String evtType = evt.Type__c;
            List<TB_Outbox_Message__c> evts = recordsByMessageType.get(evtType);
            if (evts == null) {
                evts = new List<TB_Outbox_Message__c>();
                recordsByMessageType.put(evtType, evts);
            }
            evts.add(evt);
        }

        TB_Message_Subscription__mdt[] subscriptions = TB_OutboxMetadataProvider.getMessageSubscritionMap(
                recordsByMessageType.keySet()
            )
            .values();

        // setup an "outbox" record for each subscription
        List<TB_Subscription_Outbox__c> outboxToInsert = new List<TB_Subscription_Outbox__c>();
        for (TB_Message_Subscription__mdt sub : subscriptions) {
            if (sub.Enabled__c == false) {
                continue;
            }

            for (TB_Outbox_Message__c subEvt : recordsByMessageType.get(sub.Message_Definition__r.DeveloperName)) {
               
                TB_Subscription_Outbox__c outbox = new TB_Subscription_Outbox__c(
                    Outbox_Message__c = subEvt.Id,
                    Subscription__c = sub.DeveloperName,
                    Max_Attempts__c = sub.Max_Attempts__c,
                    Application__c = sub.Application__r.DeveloperName
                );
                // set auto TTL if configured
                if(sub.Mark_TTL_Event__c  == 'created' && sub.TTL_Offset__c != null){
                    outbox.TTL__c = System.now().addMinutes((Integer) sub.TTL_Offset__c);
                }

                outboxToInsert.add(outbox);
            }
        }
        insert outboxToInsert;

        TB_OutboxRelayQueuable.enqueue(null);
    }
}