force-app/main/default/objects/Outbox_Message__c/Outbox_Message__c.object-meta.xml
<CustomObject>
    <description>Stores Outbox &quot;Message&quot;.  Each Message may trigger 0 or more Outbox record</description>
    <label>Outbox Message</label>
    <nameField>
        <displayFormat>OE-{0000}</displayFormat>
        <label>Outbox Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbox Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Outbox_Message__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of the message to fire.  Much match the DeveloperName of an Message Definition</description>
    <inlineHelpText>The type of the message to fire.  Much match the DeveloperName of an Message Definition</inlineHelpText>
    <label>Message Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TB_Message_Definition__mdt/TB_Message_Definition__mdt.object-meta.xml
<CustomObject>
    <description>Defines which messages can be fired in the org</description>
    <label>TB Message Definition</label>
    <pluralLabel>TB Message Definitions</pluralLabel>
</CustomObject>

force-app/main/default/objects/TB_Message_Definition__mdt/fields/Delete_When_Outbox_Empty__c.field-meta.xml
<CustomField>
    <fullName>Delete_When_Outbox_Empty__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, the TB_Subscription cleanup job will remove any &quot;Outbox Message&quot; records once all Outbox records are also deleted.</description>
    <inlineHelpText>When checked, the TB_Subscription cleanup job will remove any &quot;Outbox Message&quot; records once all Outbox records are also deleted.</inlineHelpText>
    <label>Delete when Outbox Empty</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TB_Outbox_Message__c/TB_Outbox_Message__c.object-meta.xml
<CustomObject>
    <description>Stores Outbox &quot;Message&quot;.  Each Message may trigger 0 or more Outbox record</description>
    <label>Outbox Message</label>
    <nameField>
        <displayFormat>OE-{0000}</displayFormat>
        <label>Outbox Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbox Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TB_Outbox_Message__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of the message to fire.  Much match the DeveloperName of an Message Definition</description>
    <inlineHelpText
    >The type of the message to fire.  Much match the DeveloperName of an Message Definition</inlineHelpText>
    <label>Message Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TB_Subscription_Outbox__c/TB_Subscription_Outbox__c.object-meta.xml
<CustomObject>
    <description>Transactional Outbox tracking for each subscriber of an message</description>
    <label>Subscription Outbox</label>
    <nameField>
        <label>Subscription Outbox Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Outboxes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TB_Subscription_Outbox__c/fields/Outbox_Message__c.field-meta.xml
<CustomField>
    <fullName>Outbox_Message__c</fullName>
    <description>The message this outbox item corresponds to</description>
    <inlineHelpText>The message this outbox item corresponds to</inlineHelpText>
    <label>Outbox Message</label>
    <referenceTo>TB_Outbox_Message__c</referenceTo>
    <relationshipLabel>Subscription Outboxes</relationshipLabel>
    <relationshipName>Subscription_Outboxes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TB_Subscription_Outbox__c/fields/TTL__c.field-meta.xml
<CustomField>
    <fullName>TTL__c</fullName>
    <description>This record will be removed once the TTL is passed.  Automatic TTL can be set via Subscription Metadata.

Requires automatic record deletion schedule job is setup.</description>
    <inlineHelpText>This record will be removed once the TTL is passed.  Automatic TTL can be set via Subscription Metadata.

Requires automatic record deletion schedule job is setup.</inlineHelpText>
    <label>Time To Live</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/TB_RecordCleanup.cls
global with sharing class TB_RecordCleanup implements Schedulable {
    global void execute(SchedulableContext sc) {
        cleanup();
    }

    //should we run this in the finalizer? Or just allow it to be scheduled
    public void cleanup() {
        List<TB_Subscription_Outbox__c> expiredRecords = [
            SELECT Id
            FROM TB_Subscription_Outbox__c
            WHERE TTL__c > :Date.today()
        ];
        if (!expiredRecords.isEmpty()) {
            System.debug('Removing Outbox: ' + expiredRecords.size());
            delete expiredRecords;
        }

        // find all Outbox_Message__c records which are configured in the Custom Metadata to purge when the outbox is empty
        Set<String> purgeOutboxOnEmpty = new Set<String>();
        for (TB_Message_Definition__mdt evtDef : TB_OutboxMetadataProvider.getMessageDefintionMap().values()) {
            if (evtDef.Delete_When_Outbox_Empty__c == true) {
                purgeOutboxOnEmpty.add(evtDef.DeveloperName);
            }
        }

        List<TB_Outbox_Message__c> outboxMessages = [
            SELECT Id
            FROM TB_Outbox_Message__c
            WHERE Type__c IN :purgeOutboxOnEmpty AND Id NOT IN (SELECT Outbox_Message__c FROM TB_Subscription_Outbox__c)
        ];
        if (!outboxMessages.isEmpty()) {
            System.debug('Removing Messages: ' + outboxMessages.size());
            delete outboxMessages;
        }

    }
}