force-app/main/default/objects/TB_Outbox_Message__c/TB_Outbox_Message__c.object-meta.xml
<CustomObject>
    <description>Stores Outbox &quot;Message&quot;.  Each Message may trigger 0 or more Outbox record</description>
    <label>Outbox Message</label>
    <nameField>
        <displayFormat>OE-{0000}</displayFormat>
        <label>Outbox Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbox Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TB_Outbox_Message__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description
    >The Data of the message. This maybe the Message to rely itself, or raw data to be processed further by an &quot;Message Resolver&quot; during the outbox processing.</description>
    <inlineHelpText
    >The Data of the message. This maybe the Message to rely itself, or raw data to be processed further by an &quot;Message Resolver&quot; during the outbox processing.</inlineHelpText>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

example/main/default/classes/CaseCreatedMessageResolver.cls
public class CaseCreatedMessageResolver implements TB_IOutboxMessageResolver {
    public Map<Id, Case> resolveMessages(TB_Outbox_Message__c[] messages) {
        Set<Id> caseIds = new Set<Id>();
        for (TB_Outbox_Message__c evt : messages) {
            caseIds.add(evt.Message__c);
        }

        Map<Id, Case> cases = new Map<Id, Case>([SELECT Id, Status FROM Case WHERE Id IN :caseIds]);

        Map<Id, Case> resolved = new Map<Id, Case>();
        for (TB_Outbox_Message__c msg : messages) {
            resolved.put(msg.Id, cases.get(msg.Message__c));
        }
        return resolved;
    }
}