force-app/main/default/objects/Message_Definition__mdt/Message_Definition__mdt.object-meta.xml
<CustomObject>
    <description>Defines which messages can be fired in the org</description>
    <label>Message Definition</label>
    <pluralLabel>Message Definitions</pluralLabel>
</CustomObject>

force-app/main/default/objects/Message_Subscription__mdt/Message_Subscription__mdt.object-meta.xml
<CustomObject>
    <description>Defines Subscriptions to each message.  Any time an message is fired, an outbox record will be setup for each Active subscription</description>
    <label>Message Subscription</label>
    <pluralLabel>Message Subscriptions</pluralLabel>
</CustomObject>

force-app/main/default/objects/Message_Subscription__mdt/fields/Max_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Max_Attempts__c</fullName>
    <description>Number of times to attempt the message before it is deadlettered</description>
    <inlineHelpText>Number of times to attempt the message before it is deadlettered</inlineHelpText>
    <label>Max Attempts</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Message_Subscription__mdt/fields/Message_Definition__c.field-meta.xml
<CustomField>
    <fullName>Message_Definition__c</fullName>
    <description>The Message to subscribe to</description>
    <label>Message Definition</label>
    <referenceTo>Message_Definition__mdt</referenceTo>
    <relationshipLabel>Message Subscriptions</relationshipLabel>
    <relationshipName>Message_Subscriptions</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Outbox_Message__c/Outbox_Message__c.object-meta.xml
<CustomObject>
    <description>Stores Outbox &quot;Message&quot;.  Each Message may trigger 0 or more Outbox record</description>
    <label>Outbox Message</label>
    <nameField>
        <displayFormat>OE-{0000}</displayFormat>
        <label>Outbox Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbox Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Outbox_Message__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of the message to fire.  Much match the DeveloperName of an Message Definition</description>
    <inlineHelpText>The type of the message to fire.  Much match the DeveloperName of an Message Definition</inlineHelpText>
    <label>Message Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription_Outbox__c/Subscription_Outbox__c.object-meta.xml
<CustomObject>
    <description>Transactional Outbox tracking for each subscriber of an message</description>
    <label>Subscription Outbox</label>
    <nameField>
        <label>Subscription Outbox Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Outboxes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription_Outbox__c/fields/Max_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Max_Attempts__c</fullName>
    <defaultValue>3</defaultValue>
    <description>The Maximum number of times to attempt to deliver this message.</description>
    <inlineHelpText>The Maximum number of times to attempt to deliver this message.</inlineHelpText>
    <label>Max Attempts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Subscription_Outbox__c/fields/Outbox_Message__c.field-meta.xml
<CustomField>
    <fullName>Outbox_Message__c</fullName>
    <description>The message this outbox item corresponds to</description>
    <inlineHelpText>The message this outbox item corresponds to</inlineHelpText>
    <label>Outbox Message</label>
    <referenceTo>Outbox_Message__c</referenceTo>
    <relationshipLabel>Subscription Outboxes</relationshipLabel>
    <relationshipName>Subscription_Outboxes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscription_Outbox__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <description>The subscription that this outbox message is firing for.  Should match based on name in Message Subscription Definitions</description>
    <externalId>true</externalId>
    <inlineHelpText>The subscription that this outbox message is firing for.  Should match based on name in Message Subscription Definitions</inlineHelpText>
    <label>Subscription</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OutboxMessageTriggerHandler.cls
public with sharing class OutboxMessageTriggerHandler {
  public void handle() {
    Map<String, List<Outbox_Message__c>> recordsByMessageType = new Map<String, List<Outbox_Message__c>>();
    for (Outbox_Message__c evt : (List<Outbox_Message__c>) Trigger.new) {
      // group evts by type
      String evtType = evt.Type__c;
      List<Outbox_Message__c> evts = recordsByMessageType.get(evtType);
      if (evts == null) {
        evts = new List<Outbox_Message__c>();
        recordsByMessageType.put(evtType, evts);
      }
      evts.add(evt);
    }

    // setup an "outbox" record for each subscription
    Message_Subscription__mdt[] subscriptions = [
      SELECT DeveloperName, QualifiedApiName, Message_Definition__r.DeveloperName, Max_Attempts__c
      FROM Message_Subscription__mdt
      WHERE Message_Definition__r.DeveloperName IN :recordsByMessageType.keySet()
    ];

    List<Subscription_Outbox__c> outboxToInsert = new List<Subscription_Outbox__c>();
    for (Message_Subscription__mdt sub : subscriptions) {
      for (Outbox_Message__c subEvt : recordsByMessageType.get(sub.Message_Definition__r.DeveloperName)) {
        Subscription_Outbox__c outbox = new Subscription_Outbox__c(
          Outbox_Message__c = subEvt.Id,
          Subscription__c = sub.DeveloperName,
          Max_Attempts__c = sub.Max_Attempts__c
        );
        outboxToInsert.add(outbox);
      }
    }
    insert outboxToInsert;

    // already in batch or future context... Will have to get picked up by scheduled apex cleanup job?  
    // Or we could fire an immediate message to kick off the batch?
    // if(!System.isFuture() && !System.isBatch()){
    //     // if (outboxToInsert.size() < 50) {
    //     //     OutboxRelay.executeRelayFuture(Trigger.newMap.keySet());
    //     // }else{
    //     //     System.scheduleBatch(new OutboxRelayBatch(), 'outbox:near-real-time', 1);
    //     // }
        
    // }
    if(Limits.getQueueableJobs() < Limits.getLimitQueueableJobs()){
      System.enqueueJob(new OutboxRelayQueuable());
    }
    
  }

}