force-app/main/default/objects/Message_Definition__mdt/Message_Definition__mdt.object-meta.xml
<CustomObject>
    <description>Defines which messages can be fired in the org</description>
    <label>Message Definition</label>
    <pluralLabel>Message Definitions</pluralLabel>
</CustomObject>

force-app/main/default/objects/Message_Definition__mdt/fields/Message_Resolver__c.field-meta.xml
<CustomField>
    <fullName>Message_Resolver__c</fullName>
    <description>Optional. The Fully Qualified Class name of an Message &quot;Resolver&quot; to execute.  Used to query additional data and construct message DTO in bulk.</description>
    <inlineHelpText>Optional. The Fully Qualified Class name of an Message &quot;Resolver&quot; to execute.  Used to query additional data and construct message DTO in bulk.</inlineHelpText>
    <label>Message Resolver</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Message_Subscription__mdt/Message_Subscription__mdt.object-meta.xml
<CustomObject>
    <description>Defines Subscriptions to each message.  Any time an message is fired, an outbox record will be setup for each Active subscription</description>
    <label>Message Subscription</label>
    <pluralLabel>Message Subscriptions</pluralLabel>
</CustomObject>

force-app/main/default/objects/Outbox_Message__c/Outbox_Message__c.object-meta.xml
<CustomObject>
    <description>Stores Outbox &quot;Message&quot;.  Each Message may trigger 0 or more Outbox record</description>
    <label>Outbox Message</label>
    <nameField>
        <displayFormat>OE-{0000}</displayFormat>
        <label>Outbox Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbox Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Outbox_Message__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The Data of the message. This maybe the Message to rely itself, or raw data to be processed further by an &quot;Message Resolver&quot; during the outbox processing.</description>
    <inlineHelpText>The Data of the message. This maybe the Message to rely itself, or raw data to be processed further by an &quot;Message Resolver&quot; during the outbox processing.</inlineHelpText>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Outbox_Message__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of the message to fire.  Much match the DeveloperName of an Message Definition</description>
    <inlineHelpText>The type of the message to fire.  Much match the DeveloperName of an Message Definition</inlineHelpText>
    <label>Message Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription_Outbox__c/Subscription_Outbox__c.object-meta.xml
<CustomObject>
    <description>Transactional Outbox tracking for each subscriber of an message</description>
    <label>Subscription Outbox</label>
    <nameField>
        <label>Subscription Outbox Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Outboxes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription_Outbox__c/fields/Completed_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Completed_Timestamp__c</fullName>
    <description>The timestamp which this outbox was completed (successful message on relay)</description>
    <inlineHelpText>The timestamp which this outbox was completed (successful message on relay)</inlineHelpText>
    <label>Completed Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Subscription_Outbox__c/fields/Dead_Lettered__c.field-meta.xml
<CustomField>
    <fullName>Dead_Lettered__c</fullName>
    <description>Once a message is dead lettered, Message Relay will no longer be attempted</description>
    <formula>Relay_Attempts__c &gt;  Max_Attempts__c || Manual_Deadletter__c == true</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Once a message is dead lettered, Message Relay will no longer be attempted.</inlineHelpText>
    <label>Dead Lettered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription_Outbox__c/fields/Last_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Last_Error_Message__c</fullName>
    <description>The error message returned by the last attempt of the outbox request</description>
    <inlineHelpText>The error message returned by the last attempt of the outbox request</inlineHelpText>
    <label>Last Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Subscription_Outbox__c/fields/Log__c.field-meta.xml
<CustomField>
    <fullName>Log__c</fullName>
    <description>A log of the last request attempt.  Can be written to by the outbox client</description>
    <inlineHelpText>A log of the last request attempt.  Can be written to by the outbox client</inlineHelpText>
    <label>Log</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Subscription_Outbox__c/fields/Outbox_Message__c.field-meta.xml
<CustomField>
    <fullName>Outbox_Message__c</fullName>
    <description>The message this outbox item corresponds to</description>
    <inlineHelpText>The message this outbox item corresponds to</inlineHelpText>
    <label>Outbox Message</label>
    <referenceTo>Outbox_Message__c</referenceTo>
    <relationshipLabel>Subscription Outboxes</relationshipLabel>
    <relationshipName>Subscription_Outboxes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscription_Outbox__c/fields/Relay_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Relay_Attempts__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The number of times this outbox message has been attempted</description>
    <inlineHelpText>The number of times this outbox message has been attempted</inlineHelpText>
    <label>Relay Attempts</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Subscription_Outbox__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <description>The subscription that this outbox message is firing for.  Should match based on name in Message Subscription Definitions</description>
    <externalId>true</externalId>
    <inlineHelpText>The subscription that this outbox message is firing for.  Should match based on name in Message Subscription Definitions</inlineHelpText>
    <label>Subscription</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OutboxRelayQueuable.cls
public with sharing class OutboxRelayQueuable implements Queueable, Database.AllowsCallouts {
  public OutboxRelayQueuable() {
  }

  /**
   * - Intentionally not dealing with callout Limits... This should allow the queueable to run as many outboxes as possible.
   */
  public void execute(QueueableContext ctx) {
    //TODO: confirm "FOR UPDATE" actually "locks" these records?
    // Should be Locked until at least the transactional Finalizer?
    List<Subscription_Outbox__c> outboxRecords = [
      SELECT
        Subscription__c,
        Outbox_Message__c,
        Outbox_Message__r.Message__c,
        Outbox_Message__r.Type__c,
        Log__c,
        Last_Error_Message__c,
        Relay_Attempts__c
      FROM Subscription_Outbox__c
      WHERE Completed_Timestamp__c = NULL
      AND Dead_Lettered__c = false
      // ORDER BY ???
      FOR UPDATE
    ];

    OutboxFinalizer finalizer = new OutboxFinalizer(outboxRecords.size());
    System.attachFinalizer(finalizer);

    // group messages by type to resolve
    Map<String, Outbox_Message__c[]> msgsByType = new Map<String, Outbox_Message__c[]>();
    for (Subscription_Outbox__c item : outboxRecords) {
      if (!msgsByType.containsKey(item.Outbox_Message__r.Type__c)) {
        msgsByType.put(item.Outbox_Message__r.Type__c, new List<Outbox_Message__c>{});
      }

      msgsByType.get(item.Outbox_Message__r.Type__c).add(item.Outbox_Message__r);
    }

    // transform DTO's
    Map<Id, Object> allresolvedMessages = resolveMessages(msgsByType);

    Map<String, Message_Subscription__mdt> subscriptionsMetadataMap = OutboxMetadataProvider.getMessageSubscritionMap(
      msgsByType.keySet()
    );
    
    // Process Each Outbox
    for (Subscription_Outbox__c item : outboxRecords) {
      Message_Subscription__mdt subDef = subscriptionsMetadataMap.get(item.Subscription__c);
      Map<String, Object> subConfig = OutboxMetadataProvider.getSubscriptionConfig(subDef);
      Object resolvedEvt = allresolvedMessages.get(item.Outbox_Message__c);
      OutboxRelayContext obCtx = new OutboxRelayContext(item, resolvedEvt, subConfig);

      try {
        obCtx.setAttempt();
        IOutboxRelayClient carrier = OutboxMetadataProvider.getSubscriptionRelayClient(subDef);
        carrier.send(obCtx);
        obCtx.setSuccess();
      } catch (Exception e) {
        obCtx.setError(e);
      } finally {
        //TODO: should this be added before? What happens if limit exception is thrown?
        finalizer.addResult(obCtx);
      }
    }
    // attempt to save results with Lock
    finalizer.save();
  }

  /**
   * Bulk Resolve Messages.
   */
  private static Map<Id, Object> resolveMessages(Map<String, Outbox_Message__c[]> msgsByType) {

    Map<String, Message_Definition__mdt> definitionsByLabel = OutboxMetadataProvider.getMessageDefintionMap(
      msgsByType.keySet()
    );

    //resolve Message DTO
    Map<Id, Object> allresolvedMessages = new Map<Id, Object>();
    for (String msgType : msgsByType.keySet()) {
      Message_Definition__mdt def = definitionsByLabel.get(msgType);
      Outbox_Message__c[] msgs = msgsByType.get(msgType);
      if (def.Message_Resolver__c != null) {
        IOutboxMessageResolver resolver = OutboxMetadataProvider.getMessageResolver(def);
        Map<Id, Object> resolvedMessages = resolver.resolveMessages(msgs);
        allresolvedMessages.putAll(resolvedMessages);
      }
    }
    return allresolvedMessages;
  }

  /**
   * Finalizer repsonsible for tracking state of outbox requests and persisting it.
   * Even if we run into a limit exception, the finalizer should ensure the outbox results get persisted.
   * WARNING: There is perhaps a small chance that a new OutboxRelayQueuable job could start up in the time between the origional job and the finalizer execution...
   */
  private class OutboxFinalizer implements Finalizer {
    private Integer outboxCount;
    // Id -> Success Timestamp
    private Map<Id, OutboxRelayContext> results;
    private Set<Id> saved;
    private OutboxFinalizer(Integer outboxCount) {
      this.outboxCount = outboxCount;
      saved = new Set<Id>();
      results = new Map<Id, OutboxRelayContext>();
    }

    public void addResult(OutboxRelayContext ctx) {
      results.put(ctx.outbox.id, ctx);
    }

    public Map<Id, OutboxRelayContext> getUnsavedResults() {
      Map<Id, OutboxRelayContext> unsaved = new Map<Id, OutboxRelayContext>(results);
      for (Id savedId : saved) {
        unsaved.remove(savedId);
      }
      return unsaved;
    }

    /**
     * Save Result and remove them if successful
     */
    public void save() {
      Map<Id, OutboxRelayContext> unsaved = getUnsavedResults();
      System.debug('Attempting to save results: ' + unsaved.size());

      List<Subscription_Outbox__c> outboxRecordsToUpdate = new List<Subscription_Outbox__c>();
      for (OutboxRelayContext ctx : unsaved.values()) {
        outboxRecordsToUpdate.add(ctx.outbox);
      }

      // Remove all successes from the state
      List<Database.SaveResult> results = Database.update(outboxRecordsToUpdate, false);
      for (Database.SaveResult sr : results) {
        if (sr.isSuccess()) {
          saved.add(sr.getId());
        }
      }
    }

    public void execute(FinalizerContext ctx) {
      Boolean moreWork = outboxCount > results.size();
      // Should we get a new query lock?
      Exception e = ctx.getException();
      if (e != null) {
        System.debug(
          'Queueable Terminated with Error! ' + e.getMessage() + '\\n' + e.getStackTraceString()
        );
      }

      save();

      if (moreWork) {
        if (Limits.getQueueableJobs() < Limits.getLimitQueueableJobs()) {
          System.enqueueJob(new OutboxRelayQueuable());
        }
      }
    }
  }
}