force-app/main/default/objects/Application__mdt/Application__mdt.object-meta.xml
<CustomObject>
    <description>An entity which can subscribe to messages</description>
    <label>Application</label>
    <pluralLabel>Applications</pluralLabel>
</CustomObject>

force-app/main/default/objects/Message_Definition__mdt/Message_Definition__mdt.object-meta.xml
<CustomObject>
    <description>Defines which messages can be fired in the org</description>
    <label>Message Definition</label>
    <pluralLabel>Message Definitions</pluralLabel>
</CustomObject>

force-app/main/default/objects/Message_Definition__mdt/fields/Message_Resolver__c.field-meta.xml
<CustomField>
    <fullName>Message_Resolver__c</fullName>
    <description>Optional. The Fully Qualified Class name of an Message &quot;Resolver&quot; to execute.  Used to query additional data and construct message DTO in bulk.</description>
    <inlineHelpText>Optional. The Fully Qualified Class name of an Message &quot;Resolver&quot; to execute.  Used to query additional data and construct message DTO in bulk.</inlineHelpText>
    <label>Message Resolver</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Message_Subscription__mdt/Message_Subscription__mdt.object-meta.xml
<CustomObject>
    <description>Defines Subscriptions to each message.  Any time an message is fired, an outbox record will be setup for each Active subscription</description>
    <label>Message Subscription</label>
    <pluralLabel>Message Subscriptions</pluralLabel>
</CustomObject>

force-app/main/default/objects/Message_Subscription__mdt/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <description>Application this subscription is for</description>
    <inlineHelpText>Application this subscription is for</inlineHelpText>
    <label>Application</label>
    <referenceTo>Application__mdt</referenceTo>
    <relationshipLabel>Message Subscriptions</relationshipLabel>
    <relationshipName>Message_Subscriptions</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Message_Subscription__mdt/fields/Config__c.field-meta.xml
<CustomField>
    <fullName>Config__c</fullName>
    <description>Optional. Configuration for the Subscription. Passed to the Relay Client via the context</description>
    <inlineHelpText>Optional. Configuration for the Subscription. Passed to the Relay Client via the context</inlineHelpText>
    <label>Config</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Message_Subscription__mdt/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allows Enabling/Disabling a subscription.  Determines if outbox records are created at the time the Message is inserted.  Outbox records that are already created will still attempt to send.</description>
    <inlineHelpText>Allows Enabling/Disabling a subscription.  Determines if outbox records are created at the time the Message is inserted.  Outbox records that are already created will still attempt to send.</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Message_Subscription__mdt/fields/Max_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Max_Attempts__c</fullName>
    <description>Number of times to attempt the message before it is deadlettered</description>
    <inlineHelpText>Number of times to attempt the message before it is deadlettered</inlineHelpText>
    <label>Max Attempts</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Message_Subscription__mdt/fields/Message_Definition__c.field-meta.xml
<CustomField>
    <fullName>Message_Definition__c</fullName>
    <description>The Message to subscribe to</description>
    <label>Message Definition</label>
    <referenceTo>Message_Definition__mdt</referenceTo>
    <relationshipLabel>Message Subscriptions</relationshipLabel>
    <relationshipName>Message_Subscriptions</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Message_Subscription__mdt/fields/Relay_Client__c.field-meta.xml
<CustomField>
    <fullName>Relay_Client__c</fullName>
    <description>The Fully Qualified Class name of an Relay Client.</description>
    <inlineHelpText>The Fully Qualified Class name of an Relay Client.</inlineHelpText>
    <label>Relay Client</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OutboxMetadataProvider.cls
public class OutboxMetadataProvider {
  @testVisible
  static Message_Definition__mdt[] msgDefinitions;
  public static Map<String, Message_Definition__mdt> getMessageDefintionMap(Set<String> msgTypes) {
    if (msgDefinitions == null) {
      msgDefinitions = [
        SELECT DeveloperName, QualifiedApiName, Message_Resolver__c
        FROM Message_Definition__mdt
      ];
    }

    Map<String, Message_Definition__mdt> definitionsByLabel = new Map<String, Message_Definition__mdt>();
    for (Message_Definition__mdt def : msgDefinitions) {
      definitionsByLabel.put(def.DeveloperName, def);
    }
    return definitionsByLabel;
  }

  @testVisible
  static Message_Subscription__mdt[] subscriptions;
  public static Map<String, Message_Subscription__mdt> getMessageSubscritionMap(
    Set<String> msgTypes
  ) {
    if (subscriptions == null) {
      subscriptions = [
        SELECT
          DeveloperName,
          Application__r.DeveloperName,
          Message_Definition__r.DeveloperName,
          Relay_Client__c,
          Config__c,
          Max_Attempts__c,
          Enabled__c
        FROM Message_Subscription__mdt
      ];
    }

    Map<String, Message_Subscription__mdt> subscriptionsByLabel = new Map<String, Message_Subscription__mdt>();
    for (Message_Subscription__mdt sub : subscriptions) {
      if(msgTypes.contains(sub.Message_Definition__r.DeveloperName)){
        subscriptionsByLabel.put(sub.DeveloperName, sub);
      }
    }
    return subscriptionsByLabel;
  }

  static Map<String, Map<String, Object>> configCache = new Map<String, Map<String, Object>>();
  public static Map<String, Object> getSubscriptionConfig(
    Message_Subscription__mdt subscriptionDef
  ) {
    if (configCache.containsKey(subscriptionDef.DeveloperName)) {
      return configCache.get(subscriptionDef.DeveloperName);
    }

    Map<String, Object> config = new Map<String, Object>();
    if (subscriptionDef.Config__c != null) {
      config = (Map<String, Object>) JSON.deserializeUntyped(subscriptionDef.Config__c);
    }
    configCache.put(subscriptionDef.DeveloperName, config);
    return config;
  }

  static Map<String, IOutboxRelayClient> clientCache = new Map<String, IOutboxRelayClient>();
  public static IOutboxRelayClient getSubscriptionRelayClient(
    Message_Subscription__mdt subscriptionDef
  ) {
    if (clientCache.containsKey(subscriptionDef.DeveloperName)) {
      return clientCache.get(subscriptionDef.DeveloperName);
    }

    IOutboxRelayClient client = (IOutboxRelayClient) OutboxUtils.constructFromName(
      subscriptionDef.Relay_Client__c
    );
    clientCache.put(subscriptionDef.DeveloperName, client);
    return client;
  }

  public static IOutboxMessageResolver getMessageResolver(Message_Definition__mdt def) {
    return (IOutboxMessageResolver) OutboxUtils.constructFromName(def.Message_Resolver__c);
  }
}