force-app/main/default/objects/Application__mdt/Application__mdt.object-meta.xml
<CustomObject>
    <description>An entity which can subscribe to messages</description>
    <label>Application</label>
    <pluralLabel>Applications</pluralLabel>
</CustomObject>

force-app/main/default/objects/Message_Definition__mdt/Message_Definition__mdt.object-meta.xml
<CustomObject>
    <description>Defines which messages can be fired in the org</description>
    <label>Message Definition</label>
    <pluralLabel>Message Definitions</pluralLabel>
</CustomObject>

force-app/main/default/objects/Message_Subscription__mdt/Message_Subscription__mdt.object-meta.xml
<CustomObject>
    <description>Defines Subscriptions to each message.  Any time an message is fired, an outbox record will be setup for each Active subscription</description>
    <label>Message Subscription</label>
    <pluralLabel>Message Subscriptions</pluralLabel>
</CustomObject>

force-app/main/default/objects/Message_Subscription__mdt/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allows Enabling/Disabling a subscription.  Determines if outbox records are created at the time the Message is inserted.  Outbox records that are already created will still attempt to send.</description>
    <inlineHelpText>Allows Enabling/Disabling a subscription.  Determines if outbox records are created at the time the Message is inserted.  Outbox records that are already created will still attempt to send.</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Outbox_Message__c/Outbox_Message__c.object-meta.xml
<CustomObject>
    <description>Stores Outbox &quot;Message&quot;.  Each Message may trigger 0 or more Outbox record</description>
    <label>Outbox Message</label>
    <nameField>
        <displayFormat>OE-{0000}</displayFormat>
        <label>Outbox Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbox Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Outbox_Message__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The Data of the message. This maybe the Message to rely itself, or raw data to be processed further by an &quot;Message Resolver&quot; during the outbox processing.</description>
    <inlineHelpText>The Data of the message. This maybe the Message to rely itself, or raw data to be processed further by an &quot;Message Resolver&quot; during the outbox processing.</inlineHelpText>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Outbox_Message__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of the message to fire.  Much match the DeveloperName of an Message Definition</description>
    <inlineHelpText>The type of the message to fire.  Much match the DeveloperName of an Message Definition</inlineHelpText>
    <label>Message Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription_Outbox__c/Subscription_Outbox__c.object-meta.xml
<CustomObject>
    <description>Transactional Outbox tracking for each subscriber of an message</description>
    <label>Subscription Outbox</label>
    <nameField>
        <label>Subscription Outbox Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Outboxes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription_Outbox__c/fields/Completed_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Completed_Timestamp__c</fullName>
    <description>The timestamp which this outbox was completed (successful message on relay)</description>
    <inlineHelpText>The timestamp which this outbox was completed (successful message on relay)</inlineHelpText>
    <label>Completed Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Subscription_Outbox__c/fields/Outbox_Message__c.field-meta.xml
<CustomField>
    <fullName>Outbox_Message__c</fullName>
    <description>The message this outbox item corresponds to</description>
    <inlineHelpText>The message this outbox item corresponds to</inlineHelpText>
    <label>Outbox Message</label>
    <referenceTo>Outbox_Message__c</referenceTo>
    <relationshipLabel>Subscription Outboxes</relationshipLabel>
    <relationshipName>Subscription_Outboxes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscription_Outbox__c/fields/Relay_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Relay_Attempts__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The number of times this outbox message has been attempted</description>
    <inlineHelpText>The number of times this outbox message has been attempted</inlineHelpText>
    <label>Relay Attempts</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Subscription_Outbox__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <description>The subscription that this outbox message is firing for.  Should match based on name in Message Subscription Definitions</description>
    <externalId>true</externalId>
    <inlineHelpText>The subscription that this outbox message is firing for.  Should match based on name in Message Subscription Definitions</inlineHelpText>
    <label>Subscription</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OutboxMessageTriggerTests.cls
@isTest
public class OutboxMessageTriggerTests {
  /**
   * Test the setup of outbox records when a new Outbox_Message__c record is inserted
   */
  static testMethod void testOutboxSetup() {
    //Setup an Application & Message Definition
    Application__mdt app = TransactionOutboxTestUtils.addApplication('TestApp');
    Message_Definition__mdt msgDef = TransactionOutboxTestUtils.addEventDefinition('test.message1');
    Message_Subscription__mdt enabledSubscription = TransactionOutboxTestUtils.addSubscription(
      app,
      msgDef,
      'EnabledSubscription'
    );

    Message_Subscription__mdt disabledSubscription = TransactionOutboxTestUtils.addSubscription(
      app,
      msgDef,
      'DisabledSubscription'
    );

    disabledSubscription.Enabled__c = false;

    // setup an Outbox_Message__c record
    Outbox_Message__c outboxMessage = new Outbox_Message__c();

    // set type & message
    outboxMessage.Type__c = msgDef.DeveloperName;
    outboxMessage.Message__c = 'Test Payload';

    //disable automatic queuing of job
    OutboxRelayQueuable.alreadyQueuedInContext = true;

    // insert the record
    insert outboxMessage;

    // assert that a Subscription Outbox record was created for each Subscription__mdt record related to the message type
    List<Subscription_Outbox__c> subscriptionOutboxes = [
      SELECT Id, Outbox_Message__c, Subscription__c, Relay_Attempts__c, Completed_Timestamp__c
      FROM Subscription_Outbox__c
      WHERE Outbox_Message__c = :outboxMessage.Id
    ];

    System.assertEquals(
      1,
      subscriptionOutboxes.size(),
      'There should be 1 Subscription Outbox record created for the Outbox Message record'
    );

    System.assertEquals(
      outboxMessage.Id,
      subscriptionOutboxes[0].Outbox_Message__c,
      'The Subscription Outbox record should be related to the Outbox Message record'
    );
    System.assertEquals(
      'EnabledSubscription',
      subscriptionOutboxes[0].Subscription__c,
      'The Subscription Outbox record should be related to the Subscription__mdt record with the same message type'
    );

    System.assertEquals(
      0,
      subscriptionOutboxes[0].Relay_Attempts__c,
      'The Subscription Outbox record should have 0 attempts'
    );

    System.assertEquals(
      null,
      subscriptionOutboxes[0].Completed_Timestamp__c,
      'The Subscription Outbox record should have a null completed timestamp'
    );
  }
}