force-app/main/default/objects/Application__mdt/Application__mdt.object-meta.xml
<CustomObject>
    <description>An entity which can subscribe to messages</description>
    <label>Application</label>
    <pluralLabel>Applications</pluralLabel>
</CustomObject>

force-app/main/default/objects/Message_Definition__mdt/Message_Definition__mdt.object-meta.xml
<CustomObject>
    <description>Defines which messages can be fired in the org</description>
    <label>Message Definition</label>
    <pluralLabel>Message Definitions</pluralLabel>
</CustomObject>

force-app/main/default/objects/Message_Definition__mdt/fields/Message_Resolver__c.field-meta.xml
<CustomField>
    <fullName>Message_Resolver__c</fullName>
    <description>Optional. The Fully Qualified Class name of an Message &quot;Resolver&quot; to execute.  Used to query additional data and construct message DTO in bulk.</description>
    <inlineHelpText>Optional. The Fully Qualified Class name of an Message &quot;Resolver&quot; to execute.  Used to query additional data and construct message DTO in bulk.</inlineHelpText>
    <label>Message Resolver</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Message_Subscription__mdt/Message_Subscription__mdt.object-meta.xml
<CustomObject>
    <description>Defines Subscriptions to each message.  Any time an message is fired, an outbox record will be setup for each Active subscription</description>
    <label>Message Subscription</label>
    <pluralLabel>Message Subscriptions</pluralLabel>
</CustomObject>

force-app/main/default/objects/Message_Subscription__mdt/fields/Config__c.field-meta.xml
<CustomField>
    <fullName>Config__c</fullName>
    <description>Optional. Configuration for the Subscription. Passed to the Relay Client via the context</description>
    <inlineHelpText>Optional. Configuration for the Subscription. Passed to the Relay Client via the context</inlineHelpText>
    <label>Config</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Message_Subscription__mdt/fields/Relay_Client__c.field-meta.xml
<CustomField>
    <fullName>Relay_Client__c</fullName>
    <description>The Fully Qualified Class name of an Relay Client.</description>
    <inlineHelpText>The Fully Qualified Class name of an Relay Client.</inlineHelpText>
    <label>Relay Client</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outbox_Message__c/Outbox_Message__c.object-meta.xml
<CustomObject>
    <description>Stores Outbox &quot;Message&quot;.  Each Message may trigger 0 or more Outbox record</description>
    <label>Outbox Message</label>
    <nameField>
        <displayFormat>OE-{0000}</displayFormat>
        <label>Outbox Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbox Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Outbox_Message__c/fields/Group_Id__c.field-meta.xml
<CustomField>
    <fullName>Group_Id__c</fullName>
    <description>Optional. When a &quot;Group&quot; is assigned, all Messages (across types!) will be processed in order of publishing within the group for each subscription.

If a message is dead lettered, processing cannot continue on subsequent messages in the group</description>
    <inlineHelpText>Optional. When a &quot;Group&quot; is assigned, all Messages (across types!) will be processed in order of publishing within the group for each subscription.

If a message is dead lettered, processing cannot continue on subsequent messages in the group</inlineHelpText>
    <label>Group Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outbox_Message__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The Data of the message. This maybe the Message to rely itself, or raw data to be processed further by an &quot;Message Resolver&quot; during the outbox processing.</description>
    <inlineHelpText>The Data of the message. This maybe the Message to rely itself, or raw data to be processed further by an &quot;Message Resolver&quot; during the outbox processing.</inlineHelpText>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Outbox_Message__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <displayFormat>{0}</displayFormat>
    <label>Sequence Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Outbox_Message__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of the message to fire.  Much match the DeveloperName of an Message Definition</description>
    <inlineHelpText>The type of the message to fire.  Much match the DeveloperName of an Message Definition</inlineHelpText>
    <label>Message Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription_Outbox__c/Subscription_Outbox__c.object-meta.xml
<CustomObject>
    <description>Transactional Outbox tracking for each subscriber of an message</description>
    <label>Subscription Outbox</label>
    <nameField>
        <label>Subscription Outbox Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Outboxes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription_Outbox__c/fields/Completed_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Completed_Timestamp__c</fullName>
    <description>The timestamp which this outbox was completed (successful message on relay)</description>
    <inlineHelpText>The timestamp which this outbox was completed (successful message on relay)</inlineHelpText>
    <label>Completed Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Subscription_Outbox__c/fields/Group_Id__c.field-meta.xml
<CustomField>
    <fullName>Group_Id__c</fullName>
    <description>The AppId + Group Id used to prevent processing once one of the messages in the group is dead lettered</description>
    <formula>IF(ISBLANK(Outbox_Message__r.Group_Id__c), null, Application__c + &apos;-&apos; + Outbox_Message__r.Group_Id__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The AppId + Group Id used to prevent processing once one of the messages in the group is dead lettered</inlineHelpText>
    <label>Group Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription_Outbox__c/fields/Last_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Last_Error_Message__c</fullName>
    <description>The error message returned by the last attempt of the outbox request</description>
    <inlineHelpText>The error message returned by the last attempt of the outbox request</inlineHelpText>
    <label>Last Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Subscription_Outbox__c/fields/Log__c.field-meta.xml
<CustomField>
    <fullName>Log__c</fullName>
    <description>A log of the last request attempt.  Can be written to by the outbox client</description>
    <inlineHelpText>A log of the last request attempt.  Can be written to by the outbox client</inlineHelpText>
    <label>Log</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Subscription_Outbox__c/fields/Outbox_Message__c.field-meta.xml
<CustomField>
    <fullName>Outbox_Message__c</fullName>
    <description>The message this outbox item corresponds to</description>
    <inlineHelpText>The message this outbox item corresponds to</inlineHelpText>
    <label>Outbox Message</label>
    <referenceTo>Outbox_Message__c</referenceTo>
    <relationshipLabel>Subscription Outboxes</relationshipLabel>
    <relationshipName>Subscription_Outboxes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscription_Outbox__c/fields/Relay_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Relay_Attempts__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The number of times this outbox message has been attempted</description>
    <inlineHelpText>The number of times this outbox message has been attempted</inlineHelpText>
    <label>Relay Attempts</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Subscription_Outbox__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <description>The subscription that this outbox message is firing for.  Should match based on name in Message Subscription Definitions</description>
    <externalId>true</externalId>
    <inlineHelpText>The subscription that this outbox message is firing for.  Should match based on name in Message Subscription Definitions</inlineHelpText>
    <label>Subscription</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OutboxRelayTests.cls
@isTest
public class OutboxRelayTests {
  @isTest
  static void testRelayProcessingSuccess() {
    //Setup an Application & Message Definition
    Application__mdt app = TransactionOutboxTestUtils.addApplication('TestApp');
    Message_Definition__mdt msgDef = TransactionOutboxTestUtils.addEventDefinition('test.message1');
    msgDef.Message_Resolver__c = 'TransactionOutboxTestUtils.TestResolver';
    Message_Subscription__mdt subscription = TransactionOutboxTestUtils.addSubscription(
      app,
      msgDef,
      'EnabledSubscription'
    );
    subscription.Relay_Client__c = 'TransactionOutboxTestUtils.TestClient';

    // setup an Outbox_Message__c record
    Outbox_Message__c outboxMessage = new Outbox_Message__c();

    // set type & message
    outboxMessage.Type__c = msgDef.DeveloperName;
    outboxMessage.Message__c = 'Test Payload';

    Test.startTest();
    insert outboxMessage;
    Test.stopTest();
    List<Subscription_Outbox__c> subscriptionOutboxes = [
      SELECT Id, Outbox_Message__c, Subscription__c, Relay_Attempts__c, Last_Error_Message__c, Completed_Timestamp__c
      FROM Subscription_Outbox__c
      WHERE Outbox_Message__c = :outboxMessage.Id
    ];
    System.assertEquals(1, subscriptionOutboxes.size());

    System.assertEquals(
      1,
      subscriptionOutboxes[0].Relay_Attempts__c,
      'The outbox should have been attempted once'
    );

    System.assertEquals(
      null,
      subscriptionOutboxes[0].Last_Error_Message__c,
      'There should be no error message'
    );

    System.assertNotEquals(
      null,
      subscriptionOutboxes[0].Completed_Timestamp__c,
      'The completed timestamp should not be null'
    );

    System.assertEquals(
        1,
        TransactionOutboxTestUtils.testExecuted,
        'The TestMessageResolver should have been executed once'
    );
  }

  @isTest
  static void testRelayProcessingFailure() {
    //Setup an Application & Message Definition
    Application__mdt app = TransactionOutboxTestUtils.addApplication('TestApp');
    Message_Definition__mdt msgDef = TransactionOutboxTestUtils.addEventDefinition('test.message1');
    Message_Subscription__mdt subscription = TransactionOutboxTestUtils.addSubscription(
      app,
      msgDef,
      'EnabledSubscription'
    );
    subscription.Relay_Client__c = 'TransactionOutboxTestUtils.TestClient';
    //setup client to fail
    subscription.Config__c = '{"throwError":true, "log": "hello"}';

    // setup an Outbox_Message__c record
    Outbox_Message__c outboxMessage = new Outbox_Message__c();

    // set type & message
    outboxMessage.Type__c = msgDef.DeveloperName;
    outboxMessage.Message__c = 'Test Payload';

    Test.startTest();
    insert outboxMessage;
    Test.stopTest();
    List<Subscription_Outbox__c> subscriptionOutboxes = [
      SELECT Id, Outbox_Message__c, Subscription__c, Relay_Attempts__c, Last_Error_Message__c, Completed_Timestamp__c, Log__c
      FROM Subscription_Outbox__c
      WHERE Outbox_Message__c = :outboxMessage.Id
    ];
    System.assertEquals(1, subscriptionOutboxes.size());

    System.assertEquals(
      1,
      subscriptionOutboxes[0].Relay_Attempts__c,
      'The outbox should have been attempted once'
    );

    System.assertNotEquals(
      null,
      subscriptionOutboxes[0].Last_Error_Message__c,
      'There should be an error message'
    );

    System.assertEquals(
      null,
      subscriptionOutboxes[0].Completed_Timestamp__c,
      'The completed timestamp should be null'
    );

    System.assert(
        subscriptionOutboxes[0].Log__c.contains('hello'),
        'Log should contain "hello"'
      );
  }


  @isTest
  static void testRelayProcessingGroup() {
    //Setup an Application & Message Definition
    Application__mdt app = TransactionOutboxTestUtils.addApplication('TestApp');
    Message_Definition__mdt msgDef = TransactionOutboxTestUtils.addEventDefinition('test.message1');
    Message_Subscription__mdt subscription = TransactionOutboxTestUtils.addSubscription(
      app,
      msgDef,
      'subscription1'
    );
    subscription.Relay_Client__c = 'TransactionOutboxTestUtils.TestClient';
    //setup client to fail
    subscription.Config__c = '{"throwError":true, "log": "hello"}';

    Message_Definition__mdt msgDef2 = TransactionOutboxTestUtils.addEventDefinition('test.message2');
    Message_Subscription__mdt subscription2 = TransactionOutboxTestUtils.addSubscription(
        app,
        msgDef2,
        'subscription2'
    );
    subscription2.Relay_Client__c = 'TransactionOutboxTestUtils.TestClient';

    // setup an Outbox_Message__c record
    Outbox_Message__c outboxMessage = new Outbox_Message__c();
    outboxMessage.Type__c = msgDef.DeveloperName;
    outboxMessage.Message__c = 'Test Payload';
    outboxMessage.Group_Id__c = 'group1';

    Outbox_Message__c outboxMessage2 = new Outbox_Message__c();
    outboxMessage2.Type__c = msgDef2.DeveloperName;
    outboxMessage2.Message__c = 'Test Payload';
    outboxMessage2.Group_Id__c = 'group1';

    Test.startTest();
    insert new Outbox_Message__c[]{outboxMessage, outboxMessage2};
    Test.stopTest();
    
    List<Subscription_Outbox__c> subscriptionOutboxes = [
      SELECT Id, Outbox_Message__c, Group_Id__c, Subscription__c, Relay_Attempts__c, Last_Error_Message__c, Completed_Timestamp__c, Log__c
      FROM Subscription_Outbox__c
      ORDER BY Outbox_Message__r.Sequence_Number__c
    ];
    System.assertEquals(2, subscriptionOutboxes.size());

    System.assertEquals(
        subscriptionOutboxes[0].Group_Id__c,
        subscriptionOutboxes[1].Group_Id__c,
        'Both outbox should have the same group'
    );

    System.assertEquals(
      1,
      subscriptionOutboxes[0].Relay_Attempts__c,
      'The outbox should have been attempted once'
    );

    System.assertNotEquals(
        null,
        subscriptionOutboxes[0].Last_Error_Message__c,
        'There should be an error message'
      );

    System.assertEquals(
        0,
        subscriptionOutboxes[1].Relay_Attempts__c,
        'The outbox should not have been attempted'
    );

  }
}