force-app/main/default/objects/TB_Application__mdt/TB_Application__mdt.object-meta.xml
<CustomObject>
    <description>An entity which can subscribe to messages</description>
    <label>TB Application</label>
    <pluralLabel>TB Applications</pluralLabel>
</CustomObject>

force-app/main/default/objects/TB_Message_Definition__mdt/TB_Message_Definition__mdt.object-meta.xml
<CustomObject>
    <description>Defines which messages can be fired in the org</description>
    <label>TB Message Definition</label>
    <pluralLabel>TB Message Definitions</pluralLabel>
</CustomObject>

force-app/main/default/objects/TB_Message_Definition__mdt/fields/Message_Resolver__c.field-meta.xml
<CustomField>
    <fullName>Message_Resolver__c</fullName>
    <description
    >Optional. The Fully Qualified Class name of an Message &quot;Resolver&quot; to execute.  Used to query additional data and construct message DTO in bulk.</description>
    <inlineHelpText
    >Optional. The Fully Qualified Class name of an Message &quot;Resolver&quot; to execute.  Used to query additional data and construct message DTO in bulk.</inlineHelpText>
    <label>Message Resolver</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TB_Message_Subscription__mdt/TB_Message_Subscription__mdt.object-meta.xml
<CustomObject>
    <description
    >Defines Subscriptions to each message.  Any time an message is fired, an outbox record will be setup for each Active subscription</description>
    <label>Message Subscription</label>
    <pluralLabel>Message Subscriptions</pluralLabel>
</CustomObject>

force-app/main/default/objects/TB_Message_Subscription__mdt/fields/After_Relay_Action__c.field-meta.xml
<CustomField>
    <fullName>After_Relay_Action__c</fullName>
    <description>IAfterRelayAction to run AFTER reply attempts</description>
    <inlineHelpText>IAfterRelayAction class to run AFTER reply attempts</inlineHelpText>
    <label>After Relay Action</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TB_Message_Subscription__mdt/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <description>Application this subscription is for</description>
    <inlineHelpText>Application this subscription is for</inlineHelpText>
    <label>Application</label>
    <referenceTo>TB_Application__mdt</referenceTo>
    <relationshipLabel>Message Subscriptions</relationshipLabel>
    <relationshipName>Message_Subscriptions</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/TB_Message_Subscription__mdt/fields/Config__c.field-meta.xml
<CustomField>
    <fullName>Config__c</fullName>
    <description>Optional. Configuration for the Subscription. Passed to the Relay Client via the context</description>
    <inlineHelpText
    >Optional. Configuration for the Subscription. Passed to the Relay Client via the context</inlineHelpText>
    <label>Config</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TB_Message_Subscription__mdt/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description
    >Allows Enabling/Disabling a subscription.  Determines if outbox records are created at the time the Message is inserted.  Outbox records that are already created will still attempt to send.</description>
    <inlineHelpText
    >Allows Enabling/Disabling a subscription.  Determines if outbox records are created at the time the Message is inserted.  Outbox records that are already created will still attempt to send.</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TB_Message_Subscription__mdt/fields/Isolate_Relay__c.field-meta.xml
<CustomField>
    <fullName>Isolate_Relay__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, the Relay of this record will be preformed in its own &quot;Execution Context&quot;.  This provides the ability for the Relay Client to perform DML, but may impact performance.</description>
    <inlineHelpText>When checked, the Relay of this record will be preformed in its own &quot;Execution Context&quot;.  This provides the ability for the Relay Client to perform DML, but may impact performance.</inlineHelpText>
    <label>Isolate Relay</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TB_Message_Subscription__mdt/fields/Max_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Max_Attempts__c</fullName>
    <description>Number of times to attempt the message before it is deadlettered</description>
    <inlineHelpText>Number of times to attempt the message before it is deadlettered</inlineHelpText>
    <label>Max Attempts</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TB_Message_Subscription__mdt/fields/Message_Definition__c.field-meta.xml
<CustomField>
    <fullName>Message_Definition__c</fullName>
    <description>The Message to subscribe to</description>
    <label>Message Definition</label>
    <referenceTo>TB_Message_Definition__mdt</referenceTo>
    <relationshipLabel>Message Subscriptions</relationshipLabel>
    <relationshipName>Message_Subscriptions</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/TB_Message_Subscription__mdt/fields/Relay_Client__c.field-meta.xml
<CustomField>
    <fullName>Relay_Client__c</fullName>
    <description>The Fully Qualified Class name of an Relay Client.</description>
    <inlineHelpText>The Fully Qualified Class name of an Relay Client.</inlineHelpText>
    <label>Relay Client</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TB_Message_Subscription__mdt/fields/Retry_Backoff__c.field-meta.xml
<CustomField>
    <fullName>Retry_Backoff__c</fullName>
    <defaultValue>&quot;0&quot;</defaultValue>
    <description>A comma separate array of &quot;minutes&quot; to back off on each subsequent attempt.  For example, &quot;0,0,15,60,720&quot; would retry immediately twice, then after 15 minutes, 1 hr and then continue to retry every 12 hours until there are no remaining attempts.

NOTE: The retry will not run until AFTER the specified timeout.  The actual timeout will depend on when the next relay request is queued or the timing of other new events that trigger the relay to run.</description>
    <inlineHelpText>A comma separate array of &quot;minutes&quot; to back off on each subsequent attempt.  For example, &quot;0,0,15,60,720&quot; would retry immediately twice, then after 15 minutes, 1 hr and then continue to retry every 12 hours until there are no remaining attempts.

NOTE: The retry will not run until AFTER the specified timeout.  The actual timeout will depend on when the next relay request is queued or the timing of other new events that trigger the relay to run.</inlineHelpText>
    <label>Retry Backoff</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TB_OutboxMetadataProvider.cls
public class TB_OutboxMetadataProvider {
    @testVisible
    static TB_Message_Definition__mdt[] msgDefinitions;

    public static Map<String, TB_Message_Definition__mdt> getMessageDefintionMap() {
        if (msgDefinitions == null) {
            msgDefinitions = [
                SELECT DeveloperName, QualifiedApiName, Message_Resolver__c
                FROM TB_Message_Definition__mdt
            ];
        }

        Map<String, TB_Message_Definition__mdt> definitionsByLabel = new Map<String, TB_Message_Definition__mdt>();
        for (TB_Message_Definition__mdt def : msgDefinitions) {
            definitionsByLabel.put(def.DeveloperName, def);
        }
        return definitionsByLabel;
    }

    @testVisible
    static TB_Message_Subscription__mdt[] subscriptions;
    public static Map<String, TB_Message_Subscription__mdt> getMessageSubscritionMap(Set<String> msgTypes) {
        if (subscriptions == null) {
            subscriptions = [
                SELECT
                    DeveloperName,
                    Application__r.DeveloperName,
                    Message_Definition__r.DeveloperName,
                    Relay_Client__c,
                    Config__c,
                    Max_Attempts__c,
                    Enabled__c,
                    After_Relay_Action__c,
                    Isolate_Relay__c,
                    Retry_Backoff__c
                FROM TB_Message_Subscription__mdt
            ];
        }

        Map<String, TB_Message_Subscription__mdt> subscriptionsByLabel = new Map<String, TB_Message_Subscription__mdt>();
        for (TB_Message_Subscription__mdt sub : subscriptions) {
            if (msgTypes.contains(sub.Message_Definition__r.DeveloperName)) {
                subscriptionsByLabel.put(sub.DeveloperName, sub);
            }
        }
        return subscriptionsByLabel;
    }

    static Map<String, Map<String, Object>> configCache = new Map<String, Map<String, Object>>();
    public static Map<String, Object> getSubscriptionConfig(TB_Message_Subscription__mdt subscriptionDef) {
        if (configCache.containsKey(subscriptionDef.DeveloperName)) {
            return configCache.get(subscriptionDef.DeveloperName);
        }

        Map<String, Object> config = new Map<String, Object>();
        if (subscriptionDef.Config__c != null) {
            config = (Map<String, Object>) JSON.deserializeUntyped(subscriptionDef.Config__c);
        }
        configCache.put(subscriptionDef.DeveloperName, config);
        return config;
    }

    static Map<String, Integer[]> retryBackOffCache = new Map<String, Integer[]>();
    public static DateTime getSubscriptionNextAttemptTimeStamp(TB_Message_Subscription__mdt subscriptionDef, Integer attempt) {
        if(subscriptionDef.Retry_BackOff__c == null) {
            return null;
        }

        Integer[] backoffList = retryBackOffCache.get(subscriptionDef.DeveloperName);

        // setup backoff list
        if (backoffList == null) {
            backoffList = new Integer[]{};
            for(String backOff : subscriptionDef.Retry_BackOff__c.split(',')){
                backoffList.add(Integer.valueOf(backOff));
            }
            retryBackOffCache.put(subscriptionDef.DeveloperName, backoffList);
        }

        // get current backoff and return new date that many minutes in the future
        return System.now().addMinutes(backoffList[Math.min(backoffList.size() - 1, attempt - 1)]);
    }

    static Map<String, TB_IOutboxRelayClient> clientCache = new Map<String, TB_IOutboxRelayClient>();
    public static TB_IOutboxRelayClient getSubscriptionRelayClient(TB_Message_Subscription__mdt subscriptionDef) {
        if (clientCache.containsKey(subscriptionDef.DeveloperName)) {
            return clientCache.get(subscriptionDef.DeveloperName);
        }

        TB_IOutboxRelayClient client = (TB_IOutboxRelayClient) TB_OutboxUtils.constructFromName(
            subscriptionDef.Relay_Client__c
        );
        clientCache.put(subscriptionDef.DeveloperName, client);
        return client;
    }

    public static TB_IOutboxMessageResolver getMessageResolver(TB_Message_Definition__mdt def) {
        return (TB_IOutboxMessageResolver) TB_OutboxUtils.constructFromName(def.Message_Resolver__c);
    }

    public static Map<String, TB_IAfterRelayAction> getAfterRelayActionsMap(TB_Message_Subscription__mdt[] subsMdt) {
        Map<String, TB_IAfterRelayAction> afterRelayActions = new Map<String, TB_IAfterRelayAction>();
        for (TB_Message_Subscription__mdt sub : subsMdt) {
            if (sub.After_Relay_Action__c != null) {
                afterRelayActions.put(sub.DeveloperName, (TB_IAfterRelayAction) TB_OutboxUtils.constructFromName(sub.After_Relay_Action__c));
            }
        }
        return afterRelayActions;
    }
}