force-app/main/default/objects/TB_Application__mdt/TB_Application__mdt.object-meta.xml
<CustomObject>
    <description>An entity which can subscribe to messages</description>
    <label>TB Application</label>
    <pluralLabel>TB Applications</pluralLabel>
</CustomObject>

force-app/main/default/objects/TB_Message_Definition__mdt/TB_Message_Definition__mdt.object-meta.xml
<CustomObject>
    <description>Defines which messages can be fired in the org</description>
    <label>TB Message Definition</label>
    <pluralLabel>TB Message Definitions</pluralLabel>
</CustomObject>

force-app/main/default/objects/TB_Message_Subscription__mdt/TB_Message_Subscription__mdt.object-meta.xml
<CustomObject>
    <description
    >Defines Subscriptions to each message.  Any time an message is fired, an outbox record will be setup for each Active subscription</description>
    <label>Message Subscription</label>
    <pluralLabel>Message Subscriptions</pluralLabel>
</CustomObject>

force-app/main/default/objects/TB_Message_Subscription__mdt/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <description>Application this subscription is for</description>
    <inlineHelpText>Application this subscription is for</inlineHelpText>
    <label>Application</label>
    <referenceTo>TB_Application__mdt</referenceTo>
    <relationshipLabel>Message Subscriptions</relationshipLabel>
    <relationshipName>Message_Subscriptions</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/TB_Message_Subscription__mdt/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description
    >Allows Enabling/Disabling a subscription.  Determines if outbox records are created at the time the Message is inserted.  Outbox records that are already created will still attempt to send.</description>
    <inlineHelpText
    >Allows Enabling/Disabling a subscription.  Determines if outbox records are created at the time the Message is inserted.  Outbox records that are already created will still attempt to send.</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TB_Message_Subscription__mdt/fields/Max_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Max_Attempts__c</fullName>
    <description>Number of times to attempt the message before it is deadlettered</description>
    <inlineHelpText>Number of times to attempt the message before it is deadlettered</inlineHelpText>
    <label>Max Attempts</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TB_Message_Subscription__mdt/fields/Message_Definition__c.field-meta.xml
<CustomField>
    <fullName>Message_Definition__c</fullName>
    <description>The Message to subscribe to</description>
    <label>Message Definition</label>
    <referenceTo>TB_Message_Definition__mdt</referenceTo>
    <relationshipLabel>Message Subscriptions</relationshipLabel>
    <relationshipName>Message_Subscriptions</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/TB_Outbox_Message__c/TB_Outbox_Message__c.object-meta.xml
<CustomObject>
    <description>Stores Outbox &quot;Message&quot;.  Each Message may trigger 0 or more Outbox record</description>
    <label>Outbox Message</label>
    <nameField>
        <displayFormat>OE-{0000}</displayFormat>
        <label>Outbox Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbox Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TB_Outbox_Message__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description
    >The Data of the message. This maybe the Message to rely itself, or raw data to be processed further by an &quot;Message Resolver&quot; during the outbox processing.</description>
    <inlineHelpText
    >The Data of the message. This maybe the Message to rely itself, or raw data to be processed further by an &quot;Message Resolver&quot; during the outbox processing.</inlineHelpText>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/TB_TransactionOutboxTestUtils.cls
@isTest
public class TB_TransactionOutboxTestUtils {
    public static TB_Application__mdt addApplication(String name) {
        //Setup an Application & Message Definition
        TB_Application__mdt app = new TB_Application__mdt(DeveloperName = name);
        return app;
    }

    public static TB_Message_Definition__mdt addEventDefinition(String type) {
        TB_Message_Definition__mdt msgDef = new TB_Message_Definition__mdt(DeveloperName = type);
        if (TB_OutboxMetadataProvider.msgDefinitions == null) {
            TB_OutboxMetadataProvider.msgDefinitions = new List<TB_Message_Definition__mdt>();
        }

        TB_OutboxMetadataProvider.msgDefinitions.add(msgDef);
        return msgDef;
    }

    public static TB_Message_Subscription__mdt addSubscription(
        TB_Application__mdt app,
        TB_Message_Definition__mdt msgDef,
        String name
    ) {
        TB_Message_Subscription__mdt subscription = new TB_Message_Subscription__mdt(
            DeveloperName = name,
            Max_Attempts__c = 3,
            Message_Definition__r = msgDef,
            Application__r = app,
            Enabled__c = true
        );

        if (TB_OutboxMetadataProvider.subscriptions == null) {
            TB_OutboxMetadataProvider.subscriptions = new List<TB_Message_Subscription__mdt>();
        }

        TB_OutboxMetadataProvider.subscriptions.add(subscription);
        return subscription;
    }

    public class TestClient implements TB_IOutboxRelayClient {
        public void send(TB_OutboxRelayContext ctx) {
            if (ctx.subscriptionConfig.containsKey('log')) {
                ctx.log(ctx.subscriptionConfig.get('log'));
            }
            if (ctx.subscriptionConfig.get('throwError') == true) {
                throw new TestException('Test Error');
            }
        }
    }

    @testVisible
    static Integer testExecuted = 0;
    public class TestResolver implements TB_IOutboxMessageResolver {
        public Map<Id, Object> resolveMessages(TB_Outbox_Message__c[] messages) {
            testExecuted++;
            Map<Id, Object> result = new Map<Id, Object>();
            for (TB_Outbox_Message__c msg : messages) {
                result.put(msg.Id, 'resolved:' + msg.Message__c);
            }
            return result;
        }
    }

    public class TestException extends Exception {
    }
}