force-app/main/default/objects/TB_Subscription_Outbox__c/TB_Subscription_Outbox__c.object-meta.xml
<CustomObject>
    <description>Transactional Outbox tracking for each subscriber of an message</description>
    <label>Subscription Outbox</label>
    <nameField>
        <label>Subscription Outbox Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Outboxes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TB_Subscription_Outbox__c/fields/Completed_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Completed_Timestamp__c</fullName>
    <description>The timestamp which this outbox was completed (successful message on relay)</description>
    <inlineHelpText>The timestamp which this outbox was completed (successful message on relay)</inlineHelpText>
    <label>Completed Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TB_Subscription_Outbox__c/fields/Last_Attempt__c.field-meta.xml
<CustomField>
    <fullName>Last_Attempt__c</fullName>
    <description>The Timestamp of the Last Attempt</description>
    <inlineHelpText>The Timestamp of the Last Attempt</inlineHelpText>
    <label>Last Attempt</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TB_Subscription_Outbox__c/fields/Last_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Last_Error_Message__c</fullName>
    <description>The error message returned by the last attempt of the outbox request</description>
    <inlineHelpText>The error message returned by the last attempt of the outbox request</inlineHelpText>
    <label>Last Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TB_Subscription_Outbox__c/fields/Log__c.field-meta.xml
<CustomField>
    <fullName>Log__c</fullName>
    <description>A log of the last request attempt.  Can be written to by the outbox client</description>
    <inlineHelpText>A log of the last request attempt.  Can be written to by the outbox client</inlineHelpText>
    <label>Log</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TB_Subscription_Outbox__c/fields/Next_Attempt_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Next_Attempt_Timestamp__c</fullName>
    <description>The earliest timestamp that the outbox may be attempted again.  If null, will attempt ASAP.  Typically set by the Subscription Retry Backoff. 
 
NOTE: How soon after this timestamp the attempt is actually made will dependent on when the relay job is next run.</description>
    <inlineHelpText>The earliest timestamp that the outbox may be attempted again.  If null, will attempt ASAP.  Typically set by the Subscription Retry Backoff. 
 
NOTE: How soon after this timestamp the attempt is actually made will dependent on when the relay job is next run.</inlineHelpText>
    <label>Next Attempt Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TB_Subscription_Outbox__c/fields/Relay_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Relay_Attempts__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The number of times this outbox message has been attempted</description>
    <inlineHelpText>The number of times this outbox message has been attempted</inlineHelpText>
    <label>Relay Attempts</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TB_OutboxRelayContext.cls
public class TB_OutboxRelayContext {
    
    /**
     * The Outbox record that is being relayed
     * Contains raw information about the subscription and the message
     */
    public TB_Subscription_Outbox__c outbox;

    /**
     * The Configuration field from the subscription after being passed through `JSON.deserializeUntyped`
     */
    public Map<String, Object> subscriptionConfig;
    
    /* 
    * Populated by the IOutboxMessageResolver. Null if no resolver is configured.
    * WARNING: This must be Serializable!
    */ 
    public Object resolvedMessage;

    /* 
    * Generic Object that can be used to store results to be used by an IAfterRelayAction
    * WARNING: This must be Serializable!
    */ 
    public Object relayResult;

    public TB_OutboxRelayContext(
        TB_Subscription_Outbox__c outbox,
        Object resolvedMessage,
        Map<String, Object> subscriptionConfig
    ) {
        this.outbox = outbox;
        this.resolvedMessage = resolvedMessage;
        this.subscriptionConfig = subscriptionConfig;

        //TODO: Should this always reset? Or should we truncate the oldest lines? (split on \n & reverse before saving)
        if (this.outbox.Log__c == null) {
            this.outbox.Log__c = '';
        }
        if (this.outbox.Relay_Attempts__c == null) {
            this.outbox.Relay_Attempts__c = 0;
        }
    }

    public void setAttempt() {
        outbox.Last_Attempt__c = Datetime.Now();
        outbox.Relay_Attempts__c++;
        // reset
        this.outbox.Next_Attempt_Timestamp__c = null;
    }

    public void setResult(Object result) {
        this.relayResult = result;
    }

    public void log(Object trace) {
        outbox.Log__c += System.now() + ': ' + trace.toString() + '\n';
    }

    // will be called by OutboxRelay
    public void setError(Exception e) {
        outbox.Last_Error_Message__c = e.getMessage() + '\n' + e.getStackTraceString();
    }

    // will be called by OutboxRelay
    public void setSuccess() {
        outbox.Completed_Timestamp__c = Datetime.Now();
    }

    public boolean isComplete() {
        return outbox.Completed_Timestamp__c != null;
    }

    public DateTime getNextAttemptTimestamp() {
        return outbox.Next_Attempt_Timestamp__c;
    }

    public void setNextAttemptTimestamp(Datetime nextAttemptTimestamp) {
        outbox.Next_Attempt_Timestamp__c = nextAttemptTimestamp;
    }
}